<Project>
  <PropertyGroup>
    <Version>2026.0805.00</Version>
    <AssemblyVersion>2026.0805.00.0</AssemblyVersion>
    <FileVersion>2026.0805.00.0</FileVersion>
    <InformationalVersion>2026.0805.00</InformationalVersion>
    <Authors>Julien Bombled</Authors>
    <Copyright>Copyright 2026 Julien Bombled</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>

